version: '3.8'

services:
  frontend:
    build:
      context: /apps/web3-builders-dapp
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    

  backend:
    build:
      context: /apps/backend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "2137:2137"
    environment:
      - NODE_ENV=production

    cron-jobs:
      build:
        context: /apps/cron-jobs
        dockerfile: Dockerfile
      command: ["npm", "run", "dev"]
      environment:
        - NODE_ENV=production
    
    discord-bot:
      build:
        context: /apps/discord-bot
        dockerfile: Dockerfile
      command: ["npm", "run", "dev"]
      environment:
        - NODE_ENV=production 